name: Tests

on:
  push:
    branches:
      - devel
      - master
  pull_request:
    branches:
      - "**"

env:
  CI: true

jobs:
  run:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm test
